{"data":{
  "message":"返回成功",
  "rpyList":[
    {
      "fundingModel":"U",
      "payAmt":"160",
      "payDate":"2016-01-24",
      "trxId":"TRX0000089",
      "trxCode":"02",
      "rpyAmt":"100",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"L",
      "payAmt":"160",
      "payDate":"2016-01-24"
    },{
      "fundingModel":"L",
      "payAmt":"160",
      "payDate":"2016-01-24"
    },{
      "fundingModel":"U",
      "payAmt":"260",
      "payDate":"2016-02-24",
      "trxId":"85",
      "trxCode":"02",
      "rpyAmt":"200",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"U",
      "payAmt":"360",
      "payDate":"2016-03-24",
      "trxId":"88",
      "trxCode":"02",
      "rpyAmt":"300",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"U",
      "payAmt":"460",
      "payDate":"2016-04-24",
      "trxId":"86",
      "trxCode":"02",
      "rpyAmt":"400",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"U",
      "payAmt":"360",
      "payDate":"2016-03-24",
      "trxId":"20",
      "trxCode":"02",
      "rpyAmt":"300",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"U",
      "payAmt":"460",
      "payDate":"2016-04-24",
      "trxId":"21",
      "trxCode":"02",
      "rpyAmt":"400",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"U",
      "payAmt":"360",
      "payDate":"2016-03-24",
      "trxId":"22",
      "trxCode":"02",
      "rpyAmt":"300",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"10",
      "counterFee":"10",
      "penalty":"10",
      "insuranceFee":"10",
      "serviceCharge":"10"
    },{
      "fundingModel":"U",
      "payAmt":"460",
      "payDate":"2016-04-24",
      "trxId":"23",
      "trxCode":"02",
      "rpyAmt":"400",
      "rateFee":"10",
      "guaranteeFee":"",
      "overInt":"0",
      "counterFee":"0",
      "penalty":"0",
      "insuranceFee":"0",
      "serviceCharge":"0"
    }
  ],
  "isSuccess":"1",
  "fundingModel":"D"
},
  "msg":"操作成功",
  "flag":"1"
}
