{
    "data": {
        "message": "返回成功",
        "payAmt": "356.66",
        "fundingModel":"L",
        "yqbList": [{
            "bindType": "YQB",
            "bankNo": "YQB",
            "loanBindNo": "5610303",
            "type": "壹钱包",
            "bankName": "壹钱包",
            "cardName": "壹钱包(7238)",
            "accountName":"4666",
            "accountNoTail": "7238"
        }],
        "debitCarList":[{
            "accountNoTail":"5073",
            "loanBindNo": "5610304",
            "bankName":"建设银行",
            "cardName": "建设银行(5073)",
            "bankNo":"CCB",
            "bindType":"BANK",
            "accountName":"4666",
            "type":"储蓄卡"
        },{
            "cardName":"平安银行(6222)",
            "loanBindNo":"5610305",
            "bankNo":"PAB",
            "bindType":"BANK",
            "bankName":"平安银行",
            "accountNoTail":"6222",
            "accountName":"4666",
            "type":"储蓄卡"
        }],
        "loanList": [{
            "startCharging": "2015-12-14",
            "shouldPay": "131618.45",
            "payState": "OD",
            "loanAmt": "20000.00",
            "counterFee": "10",
            "interest": "23.30",
            "isClaim":"0",
            "isDeduct":"1",
            "loanType": "1",
            "endCharging": "2016-03-24",
            "loanDate": "2016-01-24",
            "overInt": "0.00",
            "guaranteeFee": "12.33",
            "loanId": "LIOFR0000089",
            "penalty":"90.89",
            "serviceCharge":"20",
            "serviceChargeRate":"",
            "insuranceFee":"20",
            "insuranceRate":""
        },{
            "startCharging": "2015-12-14",
            "shouldPay": "223.48",
            "payState": "TD",
            "loanAmt": "10000.00",
            "counterFee": "0",
            "interest": "20.40",
            "isClaim":"0",
            "isDeduct":"0",
            "loanType": "0",
            "endCharging": "2016-01-14",
            "loanDate": "2015-11-14",
            "overInt": "0.00",
            "guaranteeFee": "12.33",
            "loanId": "LIOFR0000089",
            "serviceCharge":"20",
            "serviceChargeRate":"",
            "insuranceFee":"20",
            "insuranceRate":""
        },{
            "startCharging": "2015-12-14",
            "shouldPay": "223.48",
            "payState": "RP",
            "loanAmt": "10000.00",
            "counterFee": "5",
            "interest": "20.40",
            "isClaim":"0",
            "isDeduct":"0",
            "loanType": "0",
            "endCharging": "2016-01-14",
            "loanDate": "2015-11-14",
            "overInt": "0.00",
            "guaranteeFee": "12.33",
            "loanId": "LIOFR0000009",
            "serviceCharge":"20",
            "serviceChargeRate":"",
            "insuranceFee":"20",
            "insuranceRate":""
        },{
            "startCharging": "2015-12-14",
            "shouldPay": "223.48",
            "payState": "RP",
            "loanAmt": "10000.00",
            "counterFee": "5",
            "interest": "20.40",
            "isClaim":"0",
            "isDeduct":"0",
            "loanType": "0",
            "endCharging": "2016-01-14",
            "loanDate": "2015-11-14",
            "overInt": "0.00",
            "guaranteeFee": "12.33",
            "loanId": "LIOFR0000009",
            "serviceCharge":"20",
            "serviceChargeRate":"",
            "insuranceFee":"20",
            "insuranceRate":""
        },{
            "startCharging": "2015-12-14",
            "shouldPay": "223.48",
            "payState": "RP",
            "loanAmt": "10000.00",
            "counterFee": "5",
            "interest": "20.40",
            "isClaim":"0",
            "isDeduct":"0",
            "loanType": "0",
            "endCharging": "2016-01-14",
            "loanDate": "2015-11-14",
            "overInt": "0.00",
            "guaranteeFee": "12.33",
            "loanId": "LIOFR0000009",
            "serviceCharge":"20",
            "serviceChargeRate":"",
            "insuranceFee":"20",
            "insuranceRate":""
        },{
            "startCharging": "2015-12-14",
            "shouldPay": "223.48",
            "payState": "SE",
            "loanAmt": "10000.00",
            "counterFee": "5",
            "interest": "20.40",
            "isClaim":"0",
            "isDeduct":"0",
            "loanType": "0",
            "endCharging": "2016-01-14",
            "loanDate": "2015-11-14",
            "overInt": "0.00",
            "guaranteeFee": "12.33",
            "loanId": "LIOFR0000010",
            "serviceCharge":"20",
            "serviceChargeRate":"",
            "insuranceFee":"20",
            "insuranceRate":""
        }
        ],
        "isOver": "1",
        "rpyBinkNo": "5610305",
        "isSuccess": "0",
        "bankCardName": "平安银行(6222)",
        "overDueCount":"2",
        "isLP":"0"
    },
    "msg": "操作成功",
    "flag": "1"
}