{
    "flag": "1",
    "msg": "操作成功",
    "data": {
        "resultCode": "1",
        "resultMsg": "返回结果信息",
        "isFirstPay": "Y",
        "infoMap": {
            "isUpdateAgreement": "N",
            "isAccountValid": "1",
            "insuranceRateCode": "A1",
            "minLoanAmt": "200",
            "rpyType": "01",
            "loanLimit": "100",
            "maxLoanAmt": "30000",
            "creditCardName": "农业银行信用卡(2447)",
            "loanBindNo": "111111",
            "rateSum": "0.042",
            "rate": "3",
            "guaranteeRate": "2.001",
            "rpyDay": "5",
            "rpyBnakName": "平安银行储蓄卡(8765)",
            "rpyBnakNo": "1",
            "fundingModel": "U",
            "cgiBankName": "重庆银行",
            "serviceCharge": "0.030",
            "premium": "0.012",
            "isLoan": "Y",
            "frequencyLimit": "10",
            "creditCardList": [{
                "cardName": "农业银行信用卡(2447)",
                "accountNoTail": "2447",
                "cardNo": "1234567890123456",
                "loanBindNo": "111111",
                "bankNo": "ABC",
                "bindType": "BANK"
            }, {
                "cardName": "平安银行信用卡(5678)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "222222",
                "bankNo": "PAB",
                "bindType": "BANK"
            }, {
              "bankNo": "CEB",
              "cardName": "光大银行信用卡(5327)",
              "bindType": "BANK",
              "loanBindNo": "3333333",
              "bankName": "光大银行",
              "accountNoTail": "5327"
            }],
            "yqbList": [{
                "cardName": "壹钱包(4321)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "1",
                "bankNo": "YQB",
                "bankName": "壹钱包",
                "bindType": "YQB"
            }],
            "debitCarList": [{
                "cardName": "浦发银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "3",
                "bankNo": "SPDB",
                "bankName": "浦发银行",
                "bindType": "BANK"
            }, {
                "cardName": "工商银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "4",
                "bankNo": "ICBC",
                "bankName": "工商银行",
                "bindType": "BANK"
            }, {
                "cardName": "上海银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "5",
                "bankNo": "SHB",
                "bankName": "上海银行",
                "bindType": "BANK"
            }, {
                "cardName": "兴业银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "6",
                "bankNo": "CIB",
                "bankName": "兴业银行",
                "bindType": "BANK"
            }, {
                "cardName": "中国建设银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "7",
                "bankNo": "CCB",
                "bankName": "中国建设银行",
                "bindType": "BANK"
            }, {
                "cardName": "中国光大银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "8",
                "bankNo": "CEB",
                "bankName": "中国光大银行",
                "bindType": "BANK"
            }, {
                "cardName": "中信银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "9",
                "bankNo": "CNCB",
                "bankName": "中信银行",
                "bindType": "BANK"
            }, {
                "cardName": "华夏银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "10",
                "bankNo": "HXB",
                "bankName": "华夏银行",
                "bindType": "BANK"
            }, {
                "cardName": "中国农业银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "11",
                "bankNo": "ABC",
                "bankName": "中国农业银行",
                "bindType": "BANK"
            }, {
                "cardName": "平安银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "1111111",
                "bankNo": "PAB",
                "bankName": "平安银行",
                "bindType": "BANK"
            }, {
                "cardName": "中国邮政储蓄银行储蓄卡(8765)",
                "cardNo": "1234567890123456",
                "accountNoTail": "1234",
                "loanBindNo": "12",
                "bankNo": "PSBC",
                "bankName": "中国邮政储蓄银行",
                "bindType": "BANK"
            }, {
                "cardName": "中国银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "13",
                "bankNo": "BOC",
                "bankName": "中国银行",
                "bindType": "BANK"
            }, {
                "cardName": "民生银行储蓄卡(8765)",
                "accountNoTail": "1234",
                "cardNo": "1234567890123456",
                "loanBindNo": "14",
                "bankNo": "CMBC",
                "bankName": "民生银行",
                "bindType": "BANK"
            }]
        }
    }
}
